Blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include(('blogpost.urls', 'blog'), namespace='blog')),
    url(r'^$', TemplateView.as_view(template_name='home.html'))

]

blogpost/urls.py
# from django.conf.urls import url
from django.urls import path
from . import views


urlpatterns = [
    path(r'', views.post_list, name='post_list'),
    path(r'<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail, name='post_detail'),
]

blogpost/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Custom manager for retrieving posts from db
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')

    author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
            max_length=10,
            choices=STATUS_CHOICES,
            default='draft'
        )

    # Managers:
    objects = models.Manager() # Default Manager
    published = PublishedManager() # Custom manager

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                args=[
                    self.publish.year,
                    self.publish.strftime('%m'),
                    self.publish.strftime('%d'),
                    self.slug
                ]
            )

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blogpost/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blogpost/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from .forms import CommentForm

# Adding pagination
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 4)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'post_list.html', {'posts': posts, 'page': page})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        slug=post,
        status='published',
        publish__year=year,
        publish__month=month,
        publish__day=day
        )
    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'post_detail.html',
                  {
                      'post': post,
                      'comments': comments,
                      'comment_form': comment_form
                  })

blogpost/templates/post_detail.html
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}


{% block content %}
    <h1>{{ post.title }}</h1>
    <p>{{ post.publish }} by {{ post.author }}</p>

    {{ post.body|linebreaks }}

    <hr>
    {% with comments.count as total_coments %}
        <h2>{{ total_coments }} comment{{ total_coments|pluralize }}</h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no coments yet.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}

{% endblock %}

blogpost/templates/post_list.html
{% extends "base.html" %}

{% block title %}
    Django Blog 2.0
{% endblock %}

{% block content %}
    <h1>Post List</h1>
    {% for post in posts %}
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        <p>{{ post.publish }} by {{ post.author }}</p>

        {{ post.body|truncatewords:25|linebreaks }}
    {% endfor %}

    {% include 'includes/pagination.html' with page=posts %}

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <title>{% block title %}{% endblock %}</title>
{#  <link href="{% static "css/bootstrap-grid.css" %}" rel="stylesheet">#}
  <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
  <link href="{% static "css/blog.css" %}" rel="stylesheet">
    <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
</head>

<body>
    {% include 'includes/navbar.html' %}
  <div id="content">
    {% block content %} {% endblock %}
  </div>
  <div id="sidebar">
    <h2>Sidebar</h2>
    <p>sidebar for blog</p>
  </div>

    <script src="{% static 'js/bootstrap.js' %}"></script>
</body>

</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <h1>Welcome to Django Blog 2.0</h1>
        <p>Blog apllication written with Django 2.0</p>
    </div>
{% endblock %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Blog-Django 2.0</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:post_list' %}">Posts</a>
      </li>

    </ul>
  </div>
</nav>

templates/includes/pagination.html
{#<div class="pagination">#}
{#    <span class="step-links">#}
{#        {% if page.has_previous %}#}
{#            <a href="?page={{ page.previous_page_number }}">Previous</a>#}
{#        {% endif %}#}
{#        <span class="current">#}
{#            Page {{ page.number }} of {{ page.paginator.num_pages }}.#}
{#        </span>#}
{#        {% if page.has_next %}#}
{#            <a href="?page={{ page.next_page_number }}">Next</a>#}
{#        {% endif %}#}
{#    </span>#}
{#</div>#}

<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">next</a>
            <a href="?page={{ page.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>